/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    var papitas:String = "papas"
    val cruza:String = "cruza"
    val edad = 15
    val cond = true
    println("soy el $papitas")
    println("soy el $cruza y tengo ${edad + 1} y es $cond")
}
